### ISSUE TITLE
Implement a new success banner for Etcher Pro

### ISSUE THREAD

**Issue by jviotti** [balena-io/etcher#2266]
This banner should not contain external links, since the user won't be able to follow it. It can be used for promotional purposes, or to perform an action from within the banner.

**Comment by lurch** [comment]
Connects to https://github.com/resin-io/etcher-homepage

**Comment by lurch** [comment]
And it's just occurred to me that having an Etcher-Pro-specific success banner also also makes sense from a marketing point of view, because you might want to continue to promote Etcher Pro on the regular Etcher banner, but there's no point advertising Etcher Pro on the success banner that would appear on an Etcher Pro itself :wink: (IYSWIM)

**Comment by konmouz** [comment]
Prepare screens - @konmouz

**Comment by jviotti** [comment]
Closing stale issues
