### ISSUE TITLE
Automated repository testing

### ISSUE THREAD

**Issue by fearphage** [balena-io/etcher#2761]
It seems like there are several issues that have broken the (Debian?) repository:

![image](https://user-images.githubusercontent.com/23887/57020699-bdf7cc00-6bef-11e9-980f-468eabe62e00.png)

Is there an automated (CI-able) way to confirm this is working so the owners don't have to find out from user bug reports?

**Comment by lurch** [comment]
IIRC most of the "can't install from repo" issues tend to be due to temporary failures of an external GPG keyserver, which I don't think the Etcher team can do much about?

**Comment by fearphage** [comment]
I scanned a few and they seemed to be due to missing files like the currently open #2458. That's why I thought it would be testable to make sure things are well-formed before we call a release "done".

**Comment by lurch** [comment]
AFAICT the missing directory in #2458 is related to etcher-electron_1.4.4 and I think the Etcher packaging "stuff" has changed significantly since then?

**Comment by thundron** [comment]
We changed quite a lot of stuff since then, and are still refining the process but generally if you see an error wrt downloading the packages from the repositories (deb and rpm), it's usually an issue with either ubuntu's apt(-get) or keyservers.
Missing versions are due to the fact that we don't release deb|rpm packages *as often*, but it's on my to-do list.
We also just released a new auto-update feature for the AppImage package, so that's generally our main focus
