### ISSUE TITLE
Slow download

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [balena-io/etcher#2910]
Hi i have issue with download speed (20-50 KB/s), the problem is not with me bcs steam, uplay or other programs downloaded through browser goes with about 1/2 MB/s

**Comment by lurch** [comment]
See #2083 and #2336

**Comment by TheEpicNoobZilla** [comment]
Maybe it was my internet, because today it's downloading with 300/400 KB/s

**Comment by myhd** [comment]
Super slow 1990s modem speed with Github download from Germany. Estimated download time of 14 hours. VPN switch to Netherlands fixed it. But why?

**Comment by gbirke** [comment]
@myhd If you are a customer of Deutsche Telekom, it's very likely that it's because they have monopolistic peering agreements with the rest many ISPs (they want everyone to pay them for traffic, instead of saying "I'll route yours if you route mine, in the end it'll balance out"). Their connection the the big connection Hub DE-CIX is 1/20th of what other providers have. Your VPN provider probably has both a favorable peering agreement and a good connection to DE-CIX
