### ISSUE TITLE
Broken update version logic

### ISSUE THREAD

**Issue by eugenemedvediev** [balena-io/etcher#2956]
- 1.5.59 
- MacOS Catalina 10.15.1 
- Custom based on 
- Update for version 1.5.59 is not available (latest version: 1.5.60, downgrade is disallowed).
So according to application logic, 1.5.60 is lower than 1.5.59 which is wrong

**Comment by thundron** [comment]
That's the expected behaviour: not all versions go through the auto-updater, only those that we tag for release

**Comment by FlorinAndrei** [comment]
> only those that we tag for release

@thundron 

Which are those?

I downloaded the app from its main website, installed it, expected it to auto-update - never did. I had to update it manually.

**Comment by eugenemedvediev** [comment]
It was an obvious message from balenaEtcher logs that it does not allow DOWNGRADES. Does it mean 1.5.60 is Downgrade for 1.5.59 ???

**Comment by FlorinAndrei** [comment]
Guys, all this "some versions are updated, some are not" business is quite confusing to regular users.

Could y'all switch to a simpler upgrade / version policy? Thanks.

**Comment by lurch** [comment]
IIRC this policy was chosen so that if there were any accidental bugs in a new release of Etcher, not everyone would be immediately auto-updated to the (possibly buggy) version automatically. I _think_ once a version has proven itself to be "reliable enough", they then push that version into the auto-update process :grey_question: 
But I don't work for Etcher, so I can't be certain.

@thundron I expect people are getting confused by different versions of Etcher being available in different places. Maybe if there was a publicly-visible list (e.g. on the [wiki](https://github.com/balena-io/etcher/wiki) ?) of which Etcher versions are available where, _maybe_ people would be less confused? :man_shrugging:

**Comment by npmstart-pray** [comment]
> > only those that we tag for release
> 
> @thundron
> 
> Which are those?
> 
> I downloaded the app from its main website, installed it, expected it to auto-update - never did. I had to update it manually.

same here...three times now.  and I've got all three in my /applications menu.  they lock my machine, forcing me to reboot.

**Comment by lurch** [comment]
> they lock my machine, forcing me to reboot.

Maybe you should create a new issue for reporting that?

**Comment by lurch** [comment]
I believe #2996 is a good example of why each new version is not pushed through auto-update automatically :wink:
