### ISSUE TITLE
failed to burn

### ISSUE THREAD

**Issue by ParkerLouis42** [balena-io/etcher#3091]
- **Etcher version:**  1.5.79
- **Operating system and architecture:** win 10 pro laptop
- **Image flashed:**  2020-02-13-raspbian-buster-full
- **Do you see any meaningful error information in the DevTools?** 

I've tried two different holders with no success.  says zOops something went wrong with the flash.  it happens right at the beginning

**Comment by icanotc** [comment]
same issue but it can actually validate
but the partition wont show

**Comment by lurch** [comment]
@icanotc What exactly do you mean by "the partition wont show" ? Note that Windows is unable to access Linux-format partitions.

**Comment by icanotc** [comment]
@lurch its "not partitioned" under windows

**Comment by lurch** [comment]
@icanotc Depending on which image you're writing, it might be a variant of this problem? https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#flashing-ubuntu-isos

**Comment by icanotc** [comment]
@lurch nope i tried several images and rufus never gives me a problem

**Comment by lurch** [comment]
@icanotc That's because Rufus works in a different way - it formats the drive first, and then extracts the files out of the raw image onto the formatted drive. The same way as unetbootin works #413
However this approach only works with Linux images in a specific format.

Etcher works by just copying the raw image directly onto the drive - the same way as Win32DiskImager works. This approach works with **any** disk image.

@thundron Seems like this might be a good addition to the FAQ?
