### ISSUE TITLE
Etcher killed my 2 usb sticks in a single day

### ISSUE THREAD

**Issue by 3axap4eHko** [balena-io/etcher#3276]
- **Etcher version: 1.5.102** 
- **Operating system and architecture: Windows 10 x64 2004** 
- **Image flashed: ubuntu-20.04.1-desktop-amd64.iso** 
- **Do you see any meaningful error information in the DevTools? NO** 

I started writing ubuntu image on the first drive and it was throwing me an error
![image](https://user-images.githubusercontent.com/1630657/89923233-4a07ea00-dbce-11ea-8908-9698440a538e.png)
Now it's dead. Once I tried to use the second drive it did the same.
So I have 2 broken drives.

**UPD 1**:

Event Log VDS Basic  Provider:
`Cannot zero sectors on disk \\?\PhysicalDrive1. Error code: 5@0101000F`

**UPD 2**:
Repaired by the following diskpart script:
```
select disk 1
convert gpt
create partition primary
format quick fs=ntfs
```

**Comment by thundron** [comment]
This can be due to several reasons (which are not related to Etcher), for example Windows locking your drive so it's write-protected, along with other.
I'd suggest looking for the error code you see in the Event Log (`5@0101000F`) on the Microsoft forums to further investigate.
On the subject of "etcher killing USBs" please see https://www.balena.io/blog/did-etcher-break-my-usb-sd-card/

**Comment by lurch** [comment]
@thundron Nice article - probably worth adding a link to it from the Etcher README? :slightly_smiling_face:

**Comment by Uranite** [comment]
https://youtu.be/UjFEKpeVc1s
