### ISSUE TITLE
legacy in config now!!!

### ISSUE THREAD

**Issue by brunothedev** [balena-io/etcher#3370]
my pc is legacy,the etcher is uefi,congratulations!!! i search one day,because your software nots work in legacy,config need a option
"legacy or uefi" thanks your software is good

**Comment by lurch** [comment]
The legacy / uefi configuration is entirely due to the image you flash, not due to Etcher. All Etcher does is copy your image byte-for-byte onto your target drive.

Ironically, there's been several issues where people have been asking for exactly the opposite! I.e. they have an image with a legacy boot configuration, but their PC can only boot a uefi configuration https://github.com/balena-io/etcher/search?q=uefi&type=issues

Perhaps one of the alternative image-flashing programs mentioned here will be able to help? https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md

P.S. I'm not an Etcher developer, only an Etcher supporter.
