### ISSUE TITLE
Etcher Issue Installing 2GB Jetson Nano Image

### ISSUE THREAD

**Issue by AMOfficalGithub** [balena-io/etcher#3598]
- **Etcher version:** 1.5.122
- **Operating system and architecture:** Windows 10 64 bit
- **Image flashed:** 2GB Jetson Nano
- **Do you see any meaningful error information in the DevTools?** 
None

Hello everyone,

I need to install the 2GB nano Jetson image on my SD card. It's a 64 byte card so it has enough room for the 32 byte operating system. While the card is brand new and erases and writes fine, as soon as it comes to the validation part of the software a whole bunch of windows pop open of drives that don't exist on the SD card that need 'formatting'. I have to manually click through each drive to close it or format it. I made sure to be very careful NOT to format my C:\ drive or any other drives in use.

As a pre-caution, I have removed the other drives so that they aren't over-written for this second run. I've ran the software again and as soon as it gets the validation part it pops up with a bunch of windows all over again asking to format multiple drives. 

I need someone to respond to this post as soon as possible. Why is this happening?

**Comment by thundron** [comment]
@AMOfficalGithub it happens because on Windows etcher doesn't lock the drive (yet) so the OS tries to mount/change the drives as soon as the writing stops and the validation starts (that short time gap).
it's something that we want to work on in the future though - basically there's a missing flag when etcher opens the drive in the etcher-sdk, but so far we haven't been able to introduce that flag without running into issues
