### ISSUE TITLE
Etcher stuck on “Starting”

### ISSUE THREAD

**Issue by dzemper7** [balena-io/etcher#3751]
- **Etcher version:** 1.7.9
- **Operating system and architecture:** Windows 10 Pro x64
- **Image flashed:** tails-amd64-4.29.img
- **Do you see any meaningful error information in the DevTools?** It won't open with the `Ctrl+Shift+I` command.
I have tried multiple computers, ran as admin, reinstall, different versions.

**Comment by IohannRabeson** [comment]
I'm experiencing that as well

**Comment by GrantBirki** [comment]
Same here

**Comment by alanzo10** [comment]
I got the same problem but with MacOS and tails 5.0

**Comment by mcraa** [comment]
Since many of you have the "same" problem, can someone detail, what does it mean "stuck on starting"?

- by "dev tools not able to open" I could guess the etcher window is not even showing up so you can't open devtools
- by flashing a particular image I could guess it is stalling after you pressed the "Flash" button

The bulletpoints are there in the issue template for a reason. Please include the necessary information, with guessing no issue can be solved, moreover it takes the developer's time.

**Comment by mxpxgx** [comment]
Same happened to me (stalling after I click the Flash button) with v1.7.9 and macOS 10.15.7. 
I downloaded the previous version (v1.7.8) and it worked.

**Comment by rgabbo** [comment]
I experience same issue in Windows 10 using version 1.7.9. In my case Etcher is stalling after I press the "Flash" button and DevTools are shown. 

Here are logs from DevTools console:
<details>
<summary>Logs</summary>

Failed to load resource: net::ERR_FILE_NOT_FOUND
electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
log @ electron/js2c/renderer_init.js:13
gui.js:364  _____ _       _
|  ___| |     | |
| |__ | |_ ___| |__   ___ _ __
|  __|| __/ __| '_ \ / _ \ '__|
| |___| || (__| | | |  __/ |
\____/ \__\___|_| |_|\___|_|

Interested in joining the Etcher team?
Drop us a line at join+etcher@balena.io

Version = 1.7.9, Type = portable
gui.js:46 Fri Jun 03 2022 15:56:33 GMT+0200 (Ora legale dell’Europa centrale) Application start ({"packageType":"portable","version":"1.7.9","sample":0.1,"applicationSessionUuid":"0c6c136b-a385-43c6-b728-e8d0c37fa86e","flashingWorkflowUuid":"01ecdc65-5826-429d-9576-aadcfe1c7975"})
gui.js:46 [Axios v1.7.9] Transitional option 'clarifyTimeoutError' has been deprecated since v1.0.0 and will be removed in the near future
console.<computed> @ gui.js:46
gui.js:46 [Axios v1.7.9] Transitional option 'forcedJSONParsing' has been deprecated since v1.0.0 and will be removed in the near future
console.<computed> @ gui.js:46
gui.js:46 [Axios v1.7.9] Transitional option 'silentJSONParsing' has been deprecated since v1.0.0 and will be removed in the near future
console.<computed> @ gui.js:46
gui.js:46 Fri Jun 03 2022 15:56:44 GMT+0200 (Ora legale dell’Europa centrale) Open image selector ({"sample":0.1,"applicationSessionUuid":"0c6c136b-a385-43c6-b728-e8d0c37fa86e","flashingWorkflowUuid":"01ecdc65-5826-429d-9576-aadcfe1c7975"})
gui.js:46 Fri Jun 03 2022 15:56:52 GMT+0200 (Ora legale dell’Europa centrale) Select image ({"image":{"isCompressed":true,"name":"batocera-rpi4-34-20220523.img","size":3759144960,"compressedSize":1450357029,"isSizeEstimated":true,"hasMBR":true,"partitions":[{"offset":1048576,"size":3221225472,"type":12,"index":1},{"offset":3222274048,"size":536870912,"type":131,"index":2}],"extension":"gz","path":"C:\\Users\\Win10\\Downloads\\batocera-rpi4-34-20220523.img.gz","logo":false,"blockMap":false},"sample":0.1,"applicationSessionUuid":"0c6c136b-a385-43c6-b728-e8d0c37fa86e","flashingWorkflowUuid":"01ecdc65-5826-429d-9576-aadcfe1c7975"})
gui.js:46 Fri Jun 03 2022 15:56:59 GMT+0200 (Ora legale dell’Europa centrale) Flash ({"image":{"size":3759144960,"compressedSize":1450357029,"hasMBR":true,"path":"C:\\Users\\Win10\\Downloads\\batocera-rpi4-34-20220523.img.gz","partitions":[{"offset":1048576,"size":3221225472,"type":12,"index":1},{"offset":3222274048,"size":536870912,"type":131,"index":2}],"isCompressed":true,"name":"batocera-rpi4-34-20220523.img","isSizeEstimated":true,"extension":"gz"},"drives":[{"size":62534975488,"isVirtual":false,"enumerator":"USBSTOR","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive3","error":null,"isReadOnly":false,"displayName":"H:\\, MMC Card  Reader USB Device","isUAS":false,"partitionTableType":"mbr"}],"driveCount":1,"uuid":"1e5270db-e72c-4e48-9d88-88dcc53c8a77","status":"started","flashInstanceUuid":"1e5270db-e72c-4e48-9d88-88dcc53c8a77","sample":0.1,"applicationSessionUuid":"0c6c136b-a385-43c6-b728-e8d0c37fa86e","flashingWorkflowUuid":"01ecdc65-5826-429d-9576-aadcfe1c7975"})
gui.js:46 Elevating command: C:\Users\Win10\AppData\Local\Temp\289fnmVLvs5lKv6KeexfZQYqj1c\balenaEtcher.exe C:\Users\Win10\AppData\Local\Temp\289fnmVLvs5lKv6KeexfZQYqj1c\resources\app\generated\child-writer.js
gui.js:35  0 devices, 0% at 0.00 MB/s (total 0.00 MB/s)  with 0 failed devices
gui.js:46 Fri Jun 03 2022 15:57:01 GMT+0200 (Ora legale dell’Europa centrale) SafeWebview loaded ({"event":{"id":1,"url":"https://assets.balena.io/etcher-featured/index.html?borderRight=false&darkBackground=true&etcher-version=1.7.9&api-version=2&optOutAnalytics=true","method":"GET","timestamp":1654264621077.811,"resourceType":"mainFrame","ip":"2606:4700:3034::6815:1d95","fromCache":false,"statusLine":"HTTP/1.1 200","statusCode":200,"responseHeaders":{"access-control-allow-origin":["*"],"age":["184"],"alt-svc":["h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400"],"cache-control":["max-age=600"],"cf-cache-status":["DYNAMIC"],"cf-ray":["7158ef793fc91002-MRS"],"content-encoding":["br"],"content-type":["text/html; charset=utf-8"],"date":["Fri, 03 Jun 2022 13:57:01 GMT"],"expect-ct":["max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""],"expires":["Fri, 03 Jun 2022 04:51:08 GMT"],"last-modified":["Thu, 02 Jun 2022 07:18:32 GMT"],"nel":["{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}"],"report-to":["{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=eMuSIydvMiip8273nV1Tyhwv8P%2FabcCzQIPiiB6j%2F%2FGHlqYDja%2ByQHZytoro1INiOc0zRH0b59XgG59Ei3dpLI1b2p47GUJnNkEETpuXgH%2BAw%2Bn9MySO0l8xSl5MS53sGbwVp8u4UUF50hHFFVGP\"}],\"group\":\"cf-nel\",\"max_age\":604800}"],"server":["cloudflare"],"vary":["Accept-Encoding"],"via":["1.1 varnish"],"x-cache":["HIT"],"x-cache-hits":["1"],"x-fastly-request-id":["c09af26671df546dfcd5416d5001dd5d1293b944"],"x-github-request-id":["4006:3CF2:8F384E:968E30:629990E4"],"x-origin-cache":["HIT"],"x-proxy-cache":["MISS"],"x-served-by":["cache-cdg20772-CDG"],"x-timer":["S1654264621.018216,VS0,VE1"]},"referrer":"","error":"net::OK"},"sample":0.1,"applicationSessionUuid":"0c6c136b-a385-43c6-b728-e8d0c37fa86e","flashingWorkflowUuid":"01ecdc65-5826-429d-9576-aadcfe1c7975"})
gui.js:46 Successfully connected to IPC server: etcher-server-10192, socket root C:\Users\Win10\AppData\Local\Temp\
gui.js:46 Image: C:\Users\Win10\Downloads\batocera-rpi4-34-20220523.img.gz
gui.js:46 Devices: \\.\PhysicalDrive3
gui.js:46 Auto blockmapping: true
gui.js:46 Decompress first: true

</details>

If other details are needed I would be glad to help.

**Comment by petemyron** [comment]
[This ticket](https://github.com/balena-io/etcher/issues/3431#issuecomment-1089785757) has a solution that worked for me on Mac:

open Etcher with something like `sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher` so it has the enough permissions.

**Comment by esmitex** [comment]
> [This ticket](https://github.com/balena-io/etcher/issues/3431#issuecomment-1089785757) has a solution that worked for me on Mac:
> 
> open Etcher with something like `sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher` so it has the enough permissions.

Thanks a lot, it worked for me.

**Comment by zwhitchcox** [comment]
Related: https://github.com/balena-io/etcher/issues/3795#issuecomment-1220956072

**Comment by nps798** [comment]
For me, I am using Ubuntu 20.04, Etcher version 1.19.25. I solved this issue by inserting my flash drive to the rear USB ports instead of a front panel one.

**Comment by MentalGear** [comment]
This issue for me was that the drive was not formatted correctly. I used disk utility and ExFat format and then was able to flash on the drive.

**Comment by omgsideburns** [comment]
I know this is an old thread, but I ran into the same/similar issue today. 

MacOS 15.5 and the Etcher 2.1.2

Media was previously formatted AFPS.  

Reformatted media to "MS-DOS FAT" and "Master Boot Record".

**Comment by benpruitt** [comment]
Chiming in to say that I also ran into this issue on macOS 15.6.1 and Etcher 2.1.4.

My solution was similar as others above -- flash drive was originally formatted as `APFS` -- reformatting as `exFAT` resolved the issue.

**Comment by HarryD20** [comment]
> Chiming in to say that I also ran into this issue on macOS 15.6.1 and Etcher 2.1.4.
> 
> My solution was similar as others above -- flash drive was originally formatted as `APFS` -- reformatting as `exFAT` resolved the issue.

PRAISE THE LORD, YOU'VE SAVED ME, THANKS A MILLION, I MAY FINALLY REST

**Comment by ngamber** [comment]
Fixed this issue by moving my ISO off of network storage onto a local drive.

**Comment by Numerizen** [comment]
> Chiming in to say that I also ran into this issue on macOS 15.6.1 and Etcher 2.1.4.
> 
> My solution was similar as others above -- flash drive was originally formatted as `APFS` -- reformatting as `exFAT` resolved the issue.

Sir, you're a champ. Worked on M1 Tahoe here. Thanks.

**Comment by zodiac911** [comment]
> Chiming in to say that I also ran into this issue on macOS 15.6.1 and Etcher 2.1.4.
> 
> My solution was similar as others above -- flash drive was originally formatted as `APFS` -- reformatting as `exFAT` resolved the issue.

Worked

**Comment by MMehdiMousavi** [comment]
the issue is not the AFPS, you can simply unmount the AFPS manually from diskutil and it will start.
