### ISSUE TITLE
Electron 12 used by etcher is EOL (end of life)

### ISSUE THREAD

**Issue by onny** [balena-io/etcher#3767]
Electron 12 used by etcher is EOL (end of life). Installing it on NixOS results in a warning which is quite annoying. It would be great to update to a newer Electron version.

- **Etcher version:** latest
- **Operating system and architecture:** NixOS
- **Image flashed:** 
- **What do you think should have happened:** 
- **What happened:**
- **Do you see any meaningful error information in the DevTools?**

**Comment by TheRealOne78** [comment]
It's also an issue with NVIDIA graphics drivers, electron12(and below) not working correctly with gpu sandboxing, leading to this error:`[21921:0613/173615.147591:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.`

The only way to work around is to use this as root or append `--no-sandbox` or `--disable-gpu-sandboxing` arguments to the etcher executable file, which is quite hard to understand for some rookie users.

Nvidia does not seem to be the actual problem as described here: https://github.com/NVIDIA/open-gpu-kernel-modules/issues/302

and electron devs are not planning to update electron12 since it's not suported anymore: https://github.com/electron/electron/issues/34522

**Comment by rradar** [comment]
> Electron 12 used by etcher is EOL (end of life). Installing it on NixOS results in a warning which is quite annoying. 

It's not only "annoying" but a security nightmare. :bomb: 

Even critical CVE's are not fixed anymore because etcher builds their telemetry and advertising program on top of obsolete software - luckily the first package maintainers are getting rid of etcher already to protect their users. :+1:
