### ISSUE TITLE
Balena Etcher won't start

### ISSUE THREAD

**Issue by mapagm** [balena-io/etcher#3876]
- **Etcher version:** 1.7.9
- **Operating system and architecture:** KDE Neon 22.04 x64
- **Image flashed:** -

Hi. I just installed Balena Etcher via repository as shown here: https://cloudsmith.io/~balena/repos/etcher/setup/#formats-deb. It seems it installed correctly - i have balena icon in menu:
![screenshot 1668688070](https://user-images.githubusercontent.com/28437752/202446557-58e41577-f2e6-4465-bec4-724408fb756e.png)

But when I try to start it, the icon just flash for a second and nothing happens...

**Comment by ab77** [comment]
@mcraa @zwhitchcox folks, I feel like we've not got a handle on Etcher distribution... Do you know what process publishes to cloudsmith.io?

The source of truth for Etcher is https://www.balena.io/etcher/, which fetches (out of date) release from GitHub. We've also had community maintainers pull support for Homebrew, AUR, etc., since our release cadence increased.

I feel like we need a single source of truth for Etcher releases (official) and if we want to support additional package repositories, we should automate it in our CI pipeline and not rely for external contributors for distribution (core piece of Etcher).

cc @chrisys

**Comment by cheeeeee** [comment]
Try putting `balena-etcher-electron` in a terminal directly. I'm getting `/usr/lib/electron12/electron: error while loading shared libraries: libicui18n.so.71: cannot open shared object file: No such file or directory` . Haven't solved it yet. Appears to be a dependency issue.

**Comment by hillz2** [comment]
> 

It still happens to me, has anyone fixed it yet ?

**Comment by mcraa** [comment]
https://github.com/balena-io/etcher/issues/3771#issuecomment-1155239643
