### ISSUE TITLE
Not able to install etcher on ubuntu 24.10

### ISSUE THREAD

**Issue by agrawal-pratham** [balena-io/etcher#4328]
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **What do you think should have happened:** 
- **What happened:**
- **Do you see any meaningful error information in the DevTools?** 

![image](https://github.com/user-attachments/assets/3d4a21b0-385f-48a8-b050-a6e3248cfb53)
![image](https://github.com/user-attachments/assets/6ee21b7a-e826-47cd-9f21-00a895dfa6ba)
![image](https://github.com/user-attachments/assets/5fdfa995-ea26-475b-865b-eb4acf20bb5c)

**Comment by ftmiranda** [comment]
Same thing happens on Ubuntu 24.04.1
Did anyone notice that?

**Comment by TheRiseOfDavid** [comment]
I have the same problem 
* Depends: gconf-service but it is not installable
* Depends: gconf2 but it is not installable
* Depends: libgconf-2-4 but it is not installable

I attention the issue since [Problems with installation due to gconf-service and gconf2 deprecated in ubuntu 23.10](https://github.com/Eugeny/tabby/discussions/9456)

Please help me to solve it. 
![image](https://github.com/user-attachments/assets/b884bc15-9270-4cb4-ad2d-c0df998c72f0)

**Comment by lurch** [comment]
https://github.com/balena-io/etcher/issues?q=is%3Aissue+is%3Aopen+gconf2

**Comment by agrawal-pratham** [comment]
@lurch @ftmiranda @TheRiseOfDavid @otavio 
I solved it by simply installing using the zip file method.

**Comment by TheRiseOfDavid** [comment]
@agrawal-pratham Thank you for this solution
